In [1]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [ ]:
# Installing comtradeapicall package using pip
pip install comtradeapicall

In [3]:
# Assigning the subscription key to a variable
subscription_key = 'mykey'

In [6]:
# Importing the comtradeapicall module
import comtradeapicall

In [7]:
# Performing Exploratory Data Analysis (EDA) using the comtradeapicall library
# Getting final data with specified parameters
df = comtradeapicall.getFinalData(
                    subscription_key,
                    typeCode='C',
                    freqCode='M',
                    clCode='HS',
                    period=202301,
                    reporterCode=None,
                    cmdCode='392520',
                    flowCode='M,X',
                    partnerCode=None,
                    partner2Code=None,
                    customsCode=None,
                    motCode=None,
                    maxRecords=50000)

In [8]:
# Displaying the first few rows of the dataframe
df.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,M,20230101,2023,1,202301,51,None,None,M,...,8.964,False,0.0,False,184.41,NaN,184.41,0,False,True
1,C,M,20230101,2023,1,202301,51,None,None,M,...,8.964,False,0.0,False,184.41,NaN,184.41,0,False,True
2,C,M,20230101,2023,1,202301,51,None,None,M,...,8.964,False,0.0,False,184.41,NaN,184.41,0,False,True
3,C,M,20230101,2023,1,202301,51,None,None,M,...,8.964,False,0.0,False,184.41,NaN,184.41,0,False,True
4,C,M,20230101,2023,1,202301,51,None,None,M,...,8.964,False,0.0,False,184.41,NaN,184.41,0,True,False

In [11]:
# Setting the maximum number of columns to display in pandas DataFrame
pd.set_option('display.max_columns', 50)

In [12]:
df.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,flowDesc,partnerCode,partnerISO,partnerDesc,partner2Code,partner2ISO,partner2Desc,classificationCode,classificationSearchCode,isOriginalClassification,cmdCode,cmdDesc,aggrLevel,isLeaf,customsCode,customsDesc,mosCode,motCode,motDesc,qtyUnitCode,qtyUnitAbbr,qty,isQtyEstimated,altQtyUnitCode,altQtyUnitAbbr,altQty,isAltQtyEstimated,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,M,20230101,2023,1,202301,51,None,None,M,None,0,None,None,643,None,None,H6,HS,True,392520,None,None,None,C00,None,0,0,None,8,None,8.964,False,8,None,8.964,False,8.964,False,0.0,False,184.41,NaN,184.41,0,False,True
1,C,M,20230101,2023,1,202301,51,None,None,M,None,0,None,None,0,None,None,H6,HS,True,392520,None,None,None,C00,None,0,0,None,8,None,8.964,False,8,None,8.964,False,8.964,False,0.0,False,184.41,NaN,184.41,0,False,True
2,C,M,20230101,2023,1,202301,51,None,None,M,None,0,None,None,643,None,None,H6,HS,True,392520,None,None,None,C00,None,0,1000,None,8,None,8.964,False,8,None,8.964,False,8.964,False,0.0,False,184.41,NaN,184.41,0,False,True
3,C,M,20230101,2023,1,202301,51,None,None,M,None,0,None,None,0,None,None,H6,HS,True,392520,None,None,None,C00,None,0,1000,None,8,None,8.964,False,8,None,8.964,False,8.964,False,0.0,False,184.41,NaN,184.41,0,False,True
4,C,M,20230101,2023,1,202301,51,None,None,M,None,643,None,None,643,None,None,H6,HS,True,392520,None,None,None,C00,None,0,1000,None,8,None,8.964,False,8,None,8.964,False,8.964,False,0.0,False,184.41,NaN,184.41,0,True,False

In [14]:
# Displaying the column names of the DataFrame
df.columns

Index(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth', 'period',
       'reporterCode', 'reporterISO', 'reporterDesc', 'flowCode', 'flowDesc',
       'partnerCode', 'partnerISO', 'partnerDesc', 'partner2Code',
       'partner2ISO', 'partner2Desc', 'classificationCode',
       'classificationSearchCode', 'isOriginalClassification', 'cmdCode',
       'cmdDesc', 'aggrLevel', 'isLeaf', 'customsCode', 'customsDesc',
       'mosCode', 'motCode', 'motDesc', 'qtyUnitCode', 'qtyUnitAbbr', 'qty',
       'isQtyEstimated', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty',
       'isAltQtyEstimated', 'netWgt', 'isNetWgtEstimated', 'grossWgt',
       'isGrossWgtEstimated', 'cifvalue', 'fobvalue', 'primaryValue',
       'legacyEstimationFlag', 'isReported', 'isAggregate'],
      dtype='object')

In [15]:
# Displaying information about the DataFrame, including the data types of each column and memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9056 entries, 0 to 9055
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   typeCode                  9056 non-null   object
 1   freqCode                  9056 non-null   object
 2   refPeriodId               9056 non-null   int64
 3   refYear                   9056 non-null   int64
 4   refMonth                  9056 non-null   int64
 5   period                    9056 non-null   object
 6   reporterCode              9056 non-null   int64
 7   reporterISO               0 non-null      object
 8   reporterDesc              0 non-null      object
 9   flowCode                  9056 non-null   object
 10  flowDesc                  0 non-null      object
 11  partnerCode               9056 non-null   int64
 12  partnerISO                0 non-null      object
 13  partnerDesc               0 non-null      object
 14  partner2Code              9056 non-null   int64
 15  partner2ISO               0 non-null      object
 16  partner2Desc              0 non-null      object
 17  classificationCode        9056 non-null   object
 18  classificationSearchCode  9056 non-null   object
 19  isOriginalClassification  9056 non-null   bool
 20  cmdCode                   9056 non-null   object
 21  cmdDesc                   0 non-null      object
 22  aggrLevel                 0 non-null      object
 23  isLeaf                    0 non-null      object
 24  customsCode               9056 non-null   object
 25  customsDesc               0 non-null      object
 26  mosCode                   9056 non-null   object
 27  motCode                   9056 non-null   int64
 28  motDesc                   0 non-null      object
 29  qtyUnitCode               9056 non-null   int64
 30  qtyUnitAbbr               0 non-null      object
 31  qty                       9056 non-null   float64
 32  isQtyEstimated            9056 non-null   bool
 33  altQtyUnitCode            9056 non-null   int64
 34  altQtyUnitAbbr            0 non-null      object
 35  altQty                    9056 non-null   float64
 36  isAltQtyEstimated         9056 non-null   bool
 37  netWgt                    9022 non-null   float64
 38  isNetWgtEstimated         9056 non-null   bool
 39  grossWgt                  9056 non-null   float64
 40  isGrossWgtEstimated       9056 non-null   bool
 41  cifvalue                  4807 non-null   float64
 42  fobvalue                  5758 non-null   float64
 43  primaryValue              9056 non-null   float64
 44  legacyEstimationFlag      9056 non-null   int64
 45  isReported                9056 non-null   bool
 46  isAggregate               9056 non-null   bool
dtypes: bool(7), float64(7), int64(10), object(23)
memory usage: 2.8+ MB

In [16]:
# Checking for missing values in each column of the DataFrame and summing them up
df.isnull().sum()

typeCode                       0
freqCode                       0
refPeriodId                    0
refYear                        0
refMonth                       0
period                         0
reporterCode                   0
reporterISO                 9056
reporterDesc                9056
flowCode                       0
flowDesc                    9056
partnerCode                    0
partnerISO                  9056
partnerDesc                 9056
partner2Code                   0
partner2ISO                 9056
partner2Desc                9056
classificationCode             0
classificationSearchCode       0
isOriginalClassification       0
cmdCode                        0
cmdDesc                     9056
aggrLevel                   9056
isLeaf                      9056
customsCode                    0
customsDesc                 9056
mosCode                        0
motCode                        0
motDesc                     9056
qtyUnitCode                    0
qtyUnitAbbr                 9056
qty                            0
isQtyEstimated                 0
altQtyUnitCode                 0
altQtyUnitAbbr              9056
altQty                         0
isAltQtyEstimated              0
netWgt                        34
isNetWgtEstimated              0
grossWgt                       0
isGrossWgtEstimated            0
cifvalue                    4249
fobvalue                    3298
primaryValue                   0
legacyEstimationFlag           0
isReported                     0
isAggregate                    0
dtype: int64

In [17]:
# Counting the number of unique values in each column of the DataFrame
df.nunique()

typeCode                       1
freqCode                       1
refPeriodId                    1
refYear                        1
refMonth                       1
period                         1
reporterCode                  73
reporterISO                    0
reporterDesc                   0
flowCode                       2
flowDesc                       0
partnerCode                  181
partnerISO                     0
partnerDesc                    0
partner2Code                 105
partner2ISO                    0
partner2Desc                   0
classificationCode             2
classificationSearchCode       1
isOriginalClassification       1
cmdCode                        1
cmdDesc                        0
aggrLevel                      0
isLeaf                         0
customsCode                    7
customsDesc                    0
mosCode                        1
motCode                        9
motDesc                        0
qtyUnitCode                    2
qtyUnitAbbr                    0
qty                         2391
isQtyEstimated                 2
altQtyUnitCode                 4
altQtyUnitAbbr                 0
altQty                      1523
isAltQtyEstimated              1
netWgt                      2390
isNetWgtEstimated              2
grossWgt                      57
isGrossWgtEstimated            1
cifvalue                    1493
fobvalue                    1839
primaryValue                2863
legacyEstimationFlag           2
isReported                     2
isAggregate                    2
dtype: int64

In [19]:
# Retrieving the unique values in the 'customsCode' column of the DataFrame
df['customsCode'].unique()

array(['C00', 'C20', 'C03', 'C01', 'C06', 'C04', 'C05'], dtype=object)

In [20]:
# Retrieving the unique values in the 'classificationCode' column of the DataFrame
df['classificationCode'].unique()

array(['H6', 'H5'], dtype=object)

In [21]:
# Retrieving the unique values in the 'motCode' column of the DataFrame
df['motCode'].unique()

array([   0, 1000, 2100, 3200, 3000, 9900, 2000, 3100, 9200], dtype=int64)

In [22]:
df['qtyUnitCode'].unique()

array([ 8, -1], dtype=int64)

In [23]:
# Fetching the unique values in the 'qtyUnitCode' column of the DataFrame
df['qtyUnitCode'].unique()

array([ 8,  5, -1, 21], dtype=int64)

In [29]:
# Displaying the unique values in the 'legacyEstimationFlag' column of the DataFrame
df['legacyEstimationFlag'].unique()

array([0, 6], dtype=int64)

In [ ]:
# Creating a folder 
output_folder = "hscode392520"
os.makedirs(output_folder, exist_ok=True)

# Range of years from 2000 to 2023
years = range(2000, 2024)

# Counter for file numbering
file_counter = 1

# Loop for years
for year in years:
    # Range of months from January to December in the given year
    for month in range(1, 13):
        
        # Creating a string representing the period in the format "YYYYMM"
        period = f"{year}{month:02d}"
        
        # Creating a file name according to the numbering
        file_name = f"output_file_{file_counter}.csv"
        
        # API call
        df = None
        while df is None:
            try:
                df = comtradeapicall.getFinalData(
                    subscription_key,
                    typeCode='C',
                    freqCode='M',
                    clCode='HS',
                    period=period,
                    reporterCode=None,
                    cmdCode='392520',
                    flowCode='M,X',
                    partnerCode=None,
                    partner2Code=None,
                    customsCode='C00',
                    motCode=None,
                    maxRecords=50000  # Reducing the maximum number of rows
                )
            except Exception as e:
                print(f"Error in calling API: {e}")
                print(f"Retrying in 7 seconds for period: {period}")
                time.sleep(35)
        
        # Checking if the DataFrame contains data
        if not df.empty:
            # Saving the DataFrame to a CSV file
            df.to_csv(os.path.join(output_folder, file_name), index=False)
            
            # Incrementing the file counter
            file_counter += 1
        else:
            print(f"No data for the period: {period}")